routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' ,'HomeController@index');


Auth::routes();
Route::middleware('auth')->group(function () {
//    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/' , 'Web\DashboardController@show')->name('admin');
    Route::get('/admin' , 'Web\DashboardController@show')->name('admin.dashboard');

//    admin user
    Route::get('admin/user/change_pass', 'Web\AdminController@changePassword')->name('user.change_pass');
    Route::post('admin/user/update_change_pass', 'Web\AdminController@updateChangePass')->name('user.update_change_pass');
    Route::get('admin/user/profile', 'Web\AdminController@profileAuth')->name('user.profile');
    Route::resource('admin/user', 'Web\AdminController');
});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin' ,['menu_type' => 'menu_sidebar' , 'key' => 'dashboard'])

@section('content')
    <div class="container-fluid py-5">
        <div class="row">
            <div class="col">
                <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                    <div class="card-header">ĐƠN HÀNG THÀNH CÔNG</div>
                    <div class="card-body">
                        <h5 class="card-title">2.680</h5>
                        <p class="card-text">Đơn hàng giao dịch thành công</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                    <div class="card-header">ĐANG XỬ LÝ</div>
                    <div class="card-body">
                        <h5 class="card-title">10</h5>
                        <p class="card-text">Số lượng đơn hàng đang xử lý</p>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                    <div class="card-header">DOANH SỐ</div>
                    <div class="card-body">
                        <h5 class="card-title">2.5 tỷ</h5>
                        <p class="card-text">Doanh số hệ thống</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                    <div class="card-header">ĐƠN HÀNG HỦY</div>
                    <div class="card-body">
                        <h5 class="card-title">125</h5>
                        <p class="card-text">Số đơn bị hủy trong hệ thống</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- end analytic  -->
        <div class="card">
            <div class="card-header font-weight-bold">
                ĐƠN HÀNG MỚI
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Mã</th>
                        <th scope="col">Khách hàng</th>
                        <th scope="col">Sản phẩm</th>
                        <th scope="col">Số lượng</th>
                        <th scope="col">Giá trị</th>
                        <th scope="col">Trạng thái</th>
                        <th scope="col">Thời gian</th>
                        <th scope="col">Tác vụ</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>1212</td>
                        <td>
                            Phan Văn Cương <br>
                            0988859692
                        </td>
                        <td><a href="#">Samsung Galaxy A51 (8GB/128GB)</a></td>
                        <td>1</td>
                        <td>7.790.000₫</td>
                        <td><span class="badge badge-warning">Đang xử lý</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>1213</td>
                        <td>
                            Minh Anh <br>
                            0868873382
                        </td>
                        <td><a href="#">Samsung Galaxy A51 (8GB/128GB)</a></td>
                        <td>1</td>
                        <td>7.790.000₫</td>
                        <td><span class="badge badge-warning">Đang xử lý</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>1214</td>
                        <td>
                            Trần Thu Hằng <br>
                            0234343545
                        </td>
                        <td><a href="#">Điện thoại iPhone 11 Pro Max 64GB</a></td>
                        <td>1</td>
                        <td>29.490.000₫</td>
                        <td><span class="badge badge-success">Hoàn thành</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>1212</td>
                        <td>
                            Tuấn Anh <br>
                            091236768
                        </td>
                        <td><a href="#">Apple MacBook Pro Touch 2020 i5 512GB</a></td>
                        <td>1</td>
                        <td>47.990.000₫</td>
                        <td><span class="badge badge-warning">Đang xử lý</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>1214</td>
                        <td>
                            Trần Thu Hằng <br>
                            0234343545
                        </td>
                        <td><a href="#">Điện thoại iPhone 11 Pro Max 64GB</a></td>
                        <td>1</td>
                        <td>29.490.000₫</td>
                        <td><span class="badge badge-success">Hoàn thành</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>1212</td>
                        <td>
                            Tuấn Anh <br>
                            091236768
                        </td>
                        <td><a href="#">Apple MacBook Pro Touch 2020 i5 512GB</a></td>
                        <td>1</td>
                        <td>47.990.000₫</td>
                        <td><span class="badge badge-success">Hoàn thành</span></td>
                        <td>26:06:2020 14:00</td>
                        <td>
                            <a href="#" class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>

                    </tbody>
                </table>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">Trước</span>
                                <span class="sr-only">Sau</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/sidebar.blade.php
@php

    @endphp

{{--sidebar menu--}}
@if($arrayStatus['menu_type'] == 'menu_sidebar')
    <ul id="sidebar-menu">
        @foreach(\Illuminate\Support\Facades\Config::get('sidebars.menu_sidebar') as $menu_sidebar)
            <li class="nav-link {{ $menu_sidebar['key'] == $arrayStatus['key'] ? 'active' : ''}}">
                <a href="{{ !empty($menu_sidebar['route']) ? route($menu_sidebar['route'] , !empty($arrayStatus['id']) ? $arrayStatus['id'] :'' ) : '#' }}">
                    <div class="nav-link-icon d-inline-flex">
                        <i class="far {{ !empty($menu_sidebar['icon']) ? $menu_sidebar['icon'] : '' }}"></i>
                    </div>
                    {{ !empty($menu_sidebar['name']) ? $menu_sidebar['name'] : '' }}
                </a>
                <i class="arrow fas fa-angle-right"></i>
                @if(isset($menu_sidebar['children']))
                    <ul class="sub-menu">
                        @foreach($menu_sidebar['children'] as $menu_sidebar_child)
                            <li>
                                <a href="{{ !empty($menu_sidebar_child['route']) ? route($menu_sidebar_child['route'] , !empty($arrayStatus['id']) ? $arrayStatus['id'] :'' ) : '#' }}">
                                    {{ !empty($menu_sidebar_child['name']) ? $menu_sidebar_child['name'] :'' }}
                                </a></li>
                        @endforeach
                    </ul>
                @endif
            </li>
        @endforeach
        {{--        <li class="nav-link">--}}
        {{--            <a href="?view=list-post">--}}
        {{--                <div class="nav-link-icon d-inline-flex">--}}
        {{--                    <i class="far fa-folder"></i>--}}
        {{--                </div>--}}
        {{--                Trang--}}
        {{--            </a>--}}
        {{--            <i class="arrow fas fa-angle-right"></i>--}}

        {{--            <ul class="sub-menu">--}}
        {{--                <li><a href="?view=add-post">Thêm mới</a></li>--}}
        {{--                <li><a href="?view=list-post">Danh sách</a></li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
        {{--        <li class="nav-link">--}}
        {{--            <a href="?view=list-post">--}}
        {{--                <div class="nav-link-icon d-inline-flex">--}}
        {{--                    <i class="far fa-folder"></i>--}}
        {{--                </div>--}}
        {{--                Bài viết--}}
        {{--            </a>--}}
        {{--            <i class="arrow fas fa-angle-right"></i>--}}
        {{--            <ul class="sub-menu">--}}
        {{--                <li><a href="?view=add-post">Thêm mới</a></li>--}}
        {{--                <li><a href="?view=list-post">Danh sách</a></li>--}}
        {{--                <li><a href="?view=cat">Danh mục</a></li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
        {{--        <li class="nav-link">--}}
        {{--            <a href="?view=list-product">--}}
        {{--                <div class="nav-link-icon d-inline-flex">--}}
        {{--                    <i class="far fa-folder"></i>--}}
        {{--                </div>--}}
        {{--                Sản phẩm--}}
        {{--            </a>--}}
        {{--            <i class="arrow fas fa-angle-down"></i>--}}
        {{--            <ul class="sub-menu">--}}
        {{--                <li><a href="?view=add-product">Thêm mới</a></li>--}}
        {{--                <li><a href="?view=list-product">Danh sách</a></li>--}}
        {{--                <li><a href="?view=cat-product">Danh mục</a></li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
        {{--        <li class="nav-link">--}}
        {{--            <a href="?view=list-order">--}}
        {{--                <div class="nav-link-icon d-inline-flex">--}}
        {{--                    <i class="far fa-folder"></i>--}}
        {{--                </div>--}}
        {{--                Bán hàng--}}
        {{--            </a>--}}
        {{--            <i class="arrow fas fa-angle-right"></i>--}}
        {{--            <ul class="sub-menu">--}}
        {{--                <li><a href="?view=list-order">Đơn hàng</a></li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
        {{--        <li class="nav-link {{ $active == 'admin' ? 'active' : ''  }}">--}}
        {{--            <a href={{ route('user.index')  }}>--}}
        {{--                <div class="nav-link-icon d-inline-flex">--}}
        {{--                    <i class="far fa-folder"></i>--}}
        {{--                </div>--}}
        {{--                Users--}}
        {{--            </a>--}}
        {{--            <i class="arrow fas fa-angle-right"></i>--}}

        {{--            <ul class="sub-menu">--}}
        {{--                <li><a href="?view=add-user">Thêm mới</a></li>--}}
        {{--                <li><a href={{ route('user.index') }}>Danh sách</a></li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
    </ul>

    {{--sidebar menu info--}}
@elseif($arrayStatus['menu_type'] == 'menu_profile')
    <ul id="sidebar-menu">
        @foreach(\Illuminate\Support\Facades\Config::get('sidebars.menu_profile') as $menu_profile )
            <li class="nav-link {{ $menu_profile['key'] == $arrayStatus['key'] ? 'active' : ''}}">
                <a href="{{ !empty($menu_profile['route']) ? route($menu_profile['route'] , !empty($arrayStatus['id']) ? $arrayStatus['id'] :'' ) : '#'  }}"
                   @if($menu_profile['route'] == 'logout')
                   onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();"
                    @endif
                >
                    <div class="nav-link-icon d-inline-flex">
                        <i class="fas {{ !empty($menu_profile['icon']) ? $menu_profile['icon'] :'' }}"></i>
                    </div>
                    {{ !empty($menu_profile['name']) ? $menu_profile['name'] :'' }}
                </a>
                <i class="arrow fas fa-angle-right"></i>
            </li>
        @endforeach
    </ul>
@endif
<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
    @csrf
</form>