routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' ,'HomeController@index');


Auth::routes();
Route::middleware('auth')->group(function () {
//    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/' , 'Web\DashboardController@show')->name('admin');
    Route::get('/admin' , 'Web\DashboardController@show')->name('admin.dashboard');

//    admin user
    Route::get('admin/user/change_pass', 'Web\AdminController@changePassword')->name('user.change_pass');
    Route::post('admin/user/update_change_pass', 'Web\AdminController@updateChangePass')->name('user.update_change_pass');
    Route::get('admin/user/profile', 'Web\AdminController@profileAuth')->name('user.profile');
    Route::resource('admin/user', 'Web\AdminController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;


class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone' , 'address'
    ];

    protected $table = "users";
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */

    public function product()
    {
        return $this->hasMany('App\Product' , 'user_id');
    }

    public function slide()
    {
        return $this->hasMany('App\Slider' , 'user_id');
    }
}

resources/views/admin/users/change_pass.blade.php
@extends('layouts.admin', ['menu_type' => 'menu_profile' , 'key' => 'profile_change_pass'])

@section('content')
    <div id="content" class="container-fluid">
        <div class="card">
            <div class="card-header font-weight-bold">
                Đổi mật khẩu
            </div>
            <div class="card-body col-md-4">
                <form action="{{ route('user.update_change_pass') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="username">Mât khẩu cũ</label>
                        @error('password_old')
                            <div class="text text-danger">{{ $message }}</div>
                        @enderror
                        <input  class="form-control" type="password" name="password_old" id="username" >
                    </div>
                    <div class="form-group">
                        <label for="name">Mật khẩu mới</label>
                        @error('password')
                        <div class="text text-danger">{{ $message }}</div>
                        @enderror
                        <input class="form-control" type="password" name="password" id="name">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Nhập lại mật khẩu</label>
                        @error('password_confirmation')
                        <div class="text text-danger">{{ $message }}</div>
                        @enderror
                        <input class="form-control" type="password" name="password_confirmation" id="password_confirmation">
                    </div>
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/infoAdmin.blade.php
@extends('layouts.admin', ['menu_type' => 'menu_profile' , 'key' => 'profile_info'])

@section('content')
    <div id="content" class="container-fluid">
        <div class="card">
            <div class="card-header font-weight-bold">
                Chi tiết tài khoản
            </div>
            <div class="card-body col-md-4">
                <form action="{{ route('user.update' , $user->id) }}" method="POST">
                    @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="username">Tên tài khoản</label>
                        <input disabled class="form-control" type="text" name="username" id="username" value="admin">
                    </div>
                    <div class="form-group">
                        <label for="name">Họ và tên</label>
                        <input class="form-control" type="text" name="name" id="name" value="{{ $user->name }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Địa chỉ email (đăng nhập)</label>
                        <input class="form-control" type="text" name="email" id="email" value="{{ $user->email }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/list.blade.php
@extends('layouts.admin' ,['menu_type' => 'menu_sidebar' , 'key' => 'list_user'])

@section('content')
    <div id="content" class="container-fluid">
        <div class="card">
            <div class="card-header font-weight-bold d-flex justify-content-between align-items-center">
                <h5 class="m-0 ">Danh sách thành viên</h5>
                <div class="form-search form-inline">
                    <form action="#">
                        <input type="" class="form-control form-search" placeholder="Tìm kiếm">
                        <input type="submit" name="btn-search" value="Tìm kiếm" class="btn btn-primary">
                    </form>
                </div>
            </div>
            <div class="card-body">
                <div class="analytic">
                    <a href="" class="text-primary">Trạng thái 1<span class="text-muted">(10)</span></a>
                    <a href="" class="text-primary">Trạng thái 2<span class="text-muted">(5)</span></a>
                    <a href="" class="text-primary">Trạng thái 3<span class="text-muted">(20)</span></a>
                </div>
                <div class="form-action form-inline py-3">
                    <select class="form-control mr-1" id="">
                        <option>Chọn</option>
                        <option>Tác vụ 1</option>
                        <option>Tác vụ 2</option>
                    </select>
                    <input type="submit" name="btn-search" value="Áp dụng" class="btn btn-primary">
                </div>
                <table class="table table-striped table-checkall">
                    <thead>
                    <tr>
                        <th>
                            <input type="checkbox" name="checkall">
                        </th>
                        <th scope="col">#</th>
                        <th scope="col">Họ tên</th>
                        <th scope="col">Username</th>
                        <th scope="col">Email</th>
                        <th scope="col">Quyền</th>
                        <th scope="col">Ngày tạo</th>
                        <th scope="col">Tác vụ</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if($list_user->count() > 0)
                        @foreach($list_user as $key => $user)
                    <tr>
                        <td>
                            <input type="checkbox">
                        </td>
                        <th scope="row">{{ $key+1 }}</th>
                        <td>{{ $user->name  }}</td>
                        <td>{{ $user->name  }}</td>
                        <td>{{ $user->email }}</td>
                        <td>Admintrator</td>
                        <td>{{ $user->created_at  }}</td>
                        <td>
                            <a href="{{  route('user.show' , $user->id) }} " class="btn btn-success btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-danger btn-sm rounded-0 text-white" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
                <nav aria-label="Page navigation example">
                    {{ $list_user->links()  }}
                </nav>
            </div>
        </div>
    </div>
@endsection